### ISSUE TITLE
Ubuntu 14.04 Pam Module 2FA Bypass

### ISSUE THREAD

**Issue by 0xdade** [duosecurity/puppet-duo_unix#8]
The PAM unix control for pam_duo in /etc/pam.d/common-auth is being hard coded to: [success=1 default=ignore] . When I then run sudo su, it prompts me for my password, and when I enter my password correctly it then sends me a push notification. Hit ctrl-c three times and I've bypassed the need to respond to the push notification, giving me access to my root shell. I've made numerous attempts to figure out the correct PAM settings, but I haven't had any luck. Stopping the bypass also meant that successful logins & approvals were being rejected as invalid.

Working on finding a fix, figured I'd share and see if anyone else has noticed this sort of behavior or if its just something in my environment.

**Comment by jasonstrange** [comment]
I'm posting here because I can't really find any better place to do so. There was a bug report email that went out on this topic that attributed it to me but I can't seem to find it, and I was hoping it was recorded internal somewhere and that perhaps there was a copy of it that could be provided to me.
